service: serverlessgram

frameworkVersion: ">=1.1.0"

custom:
  bucket: 'serverlessgram-thiagodevvv'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  newPedido:
    handler: serverlessgram.newPedido
    events:
      - http:
          path: newPedido
          method: post
          cors: true

  addContato:
    handler: serverlessgram.addContato
    events:
      - http:
          path: addContato
          method: post
          cors: true

  cancelarPedido:
    handler: serverlessgram.alterarStatusPedido
    events:
      - http:
          path: alterarStatusPedido
          method: post
          cors: true

plugins:
  - serverless-offline
useDotenv: true
